// <auto-generated />
using System;
using Lang.Dictionary.Adapter.Postgres;
using Lang.Dictionary.Adapter.Postgres.Users;
using Lang.Dictionary.Adapter.Postgres.Words;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lang.Dictionary.Adapter.Postgres.Migrations
{
    [DbContext(typeof(LangContext))]
    [Migration("20230406202841_AddWordList")]
    partial class AddWordList
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lang.Dictionary.Adapter.Postgres.Users.UserBox", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<UserDal>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.HasKey("Id")
                        .HasName("user_id");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("Lang.Dictionary.Adapter.Postgres.WordLists.WordListDal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("word_list", (string)null);
                });

            modelBuilder.Entity("Lang.Dictionary.Adapter.Postgres.WordLists.WordToWordListDal", b =>
                {
                    b.Property<Guid>("WordId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WordListId")
                        .HasColumnType("uuid");

                    b.HasKey("WordId", "WordListId");

                    b.HasIndex("WordListId");

                    b.ToTable("word_to_word_list", (string)null);
                });

            modelBuilder.Entity("Lang.Dictionary.Adapter.Postgres.Words.WordDal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<TranslatedWordDal>("From")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("from");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<TranslatedWordDal>("To")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("to");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("word", (string)null);
                });

            modelBuilder.Entity("Lang.Dictionary.Adapter.Postgres.WordLists.WordListDal", b =>
                {
                    b.HasOne("Lang.Dictionary.Adapter.Postgres.Users.UserBox", "Owner")
                        .WithMany("WordLists")
                        .HasForeignKey("OwnerId");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Lang.Dictionary.Adapter.Postgres.WordLists.WordToWordListDal", b =>
                {
                    b.HasOne("Lang.Dictionary.Adapter.Postgres.Words.WordDal", "Word")
                        .WithMany("WordToWordLists")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lang.Dictionary.Adapter.Postgres.WordLists.WordListDal", "WordList")
                        .WithMany("WordsToWordList")
                        .HasForeignKey("WordListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Word");

                    b.Navigation("WordList");
                });

            modelBuilder.Entity("Lang.Dictionary.Adapter.Postgres.Words.WordDal", b =>
                {
                    b.HasOne("Lang.Dictionary.Adapter.Postgres.Users.UserBox", "Owner")
                        .WithMany("Words")
                        .HasForeignKey("OwnerId");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Lang.Dictionary.Adapter.Postgres.Users.UserBox", b =>
                {
                    b.Navigation("WordLists");

                    b.Navigation("Words");
                });

            modelBuilder.Entity("Lang.Dictionary.Adapter.Postgres.WordLists.WordListDal", b =>
                {
                    b.Navigation("WordsToWordList");
                });

            modelBuilder.Entity("Lang.Dictionary.Adapter.Postgres.Words.WordDal", b =>
                {
                    b.Navigation("WordToWordLists");
                });
#pragma warning restore 612, 618
        }
    }
}
