// <auto-generated />
using System;
using Lang.Dictionary.Adapter.Postgres;
using Lang.Dictionary.Adapter.Postgres.Users;
using Lang.Dictionary.Adapter.Postgres.Words;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lang.Dictionary.Adapter.Postgres.Migrations
{
    [DbContext(typeof(LangContext))]
    partial class LangContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lang.Dictionary.Adapter.Postgres.Users.UserBox", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<UserDal>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.HasKey("Id")
                        .HasName("user_id");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("Lang.Dictionary.Adapter.Postgres.Words.WordDal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<TranslatedWordDal>("From")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("from");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<TranslatedWordDal>("To")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("to");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("word", (string)null);
                });

            modelBuilder.Entity("Lang.Dictionary.Adapter.Postgres.Words.WordDal", b =>
                {
                    b.HasOne("Lang.Dictionary.Adapter.Postgres.Users.UserBox", "Owner")
                        .WithMany("Words")
                        .HasForeignKey("OwnerId");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Lang.Dictionary.Adapter.Postgres.Users.UserBox", b =>
                {
                    b.Navigation("Words");
                });
#pragma warning restore 612, 618
        }
    }
}
